#!/usr/bin/env Rscript

# Refresh the vendored Apache DataSketches C++ headers.
#
# Run from the package root:
#   Rscript tools/update-datasketches-cpp.R
#
# Remember to update package notices and release notes after refreshing.

# Pinned upstream version -- the single source of truth for what we vendor.
DATASKETCHES_VERSION <- "5.2.0"

# Top-level source distribution files that should travel with vendored code.
VENDOR_FILES <- c(
  "README.md",
  "README",
  "NOTICE",
  "NOTICE.txt",
  "LICENSE",
  "LICENSE.txt",
  "COPYING",
  "COPYRIGHT",
  "AUTHORS",
  "CONTRIBUTORS",
  "THIRD_PARTY_NOTICES",
  "DEPENDENCIES",
  "DISCLAIMER",
  "CHANGELOG.md",
  "CHANGES.md",
  "RELEASE_NOTES.md"
)

stopifnot(file.exists("DESCRIPTION"), file.exists("src"))

url <- sprintf(
  "https://github.com/apache/datasketches-cpp/archive/refs/tags/%s.tar.gz",
  DATASKETCHES_VERSION
)

tmp <- tempfile(fileext = ".tar.gz")
exdir <- tempfile("datasketches-cpp-")
on.exit(unlink(c(tmp, exdir), recursive = TRUE), add = TRUE)

message("Downloading DataSketches ", DATASKETCHES_VERSION, " ...")
utils::download.file(url, tmp, mode = "wb", quiet = TRUE)
utils::untar(tmp, exdir = exdir)

root <- file.path(exdir, sprintf("datasketches-cpp-%s", DATASKETCHES_VERSION))
if (!dir.exists(root)) {
  stop("Unexpected archive layout: ", root, " not found", call. = FALSE)
}

dest_root <- file.path("src", "datasketches")

component_dirs <- list.dirs(root, full.names = TRUE, recursive = FALSE)
components <- basename(component_dirs)[
  dir.exists(file.path(component_dirs, "include"))
]

if (length(components) == 0) {
  stop(
    "No component include directories found in upstream archive",
    call. = FALSE
  )
}

unlink(dest_root, recursive = TRUE)
dir.create(dest_root, recursive = TRUE, showWarnings = FALSE)

for (vendor_file in VENDOR_FILES) {
  from <- file.path(root, vendor_file)
  if (!file.exists(from)) {
    next
  }

  file.copy(from, dest_root, overwrite = TRUE)
  message("  vendored ", vendor_file)
}

for (component in components) {
  from <- file.path(root, component, "include")
  to <- file.path(dest_root, component, "include")
  if (!dir.exists(from)) {
    stop("Component not found in upstream archive: ", from, call. = FALSE)
  }
  unlink(to, recursive = TRUE)
  dir.create(to, recursive = TRUE, showWarnings = FALSE)
  files <- list.files(from, all.files = TRUE, full.names = TRUE, no.. = TRUE)
  file.copy(files, to, overwrite = TRUE, recursive = TRUE)
  message("  vendored ", component, "/include (", length(files), " files)")
}

# Keep the R-side native version constant in lockstep with the vendored headers,
# so write_sketch() never carries a stale `native_version`. This file is the
# single source of truth on the R side; DATASKETCHES_VERSION above is the source.
version_r <- file.path("R", "datasketches-version.R")
writeLines(
  c(
    "# Generated by tools/update-datasketches-cpp.R -- do not edit by hand.",
    "# The vendored Apache DataSketches C++ release, used as `native_version` when",
    "# writing sketch files (see persistence). Kept in lockstep with the headers by",
    "# the updater script.",
    sprintf('.datasketches_native_version <- "%s"', DATASKETCHES_VERSION)
  ),
  version_r
)
message("  wrote ", version_r, " (", DATASKETCHES_VERSION, ")")

message(
  "Done. Now update the vendored src/datasketches/NOTICE and NEWS.md to ",
  "DataSketches ",
  DATASKETCHES_VERSION,
  ", then run devtools::test()."
)
