# Generated by cpp11: do not edit by hand

aod_create_cpp <- function(lg_k, num_values, seed) {
  .Call(`_data_sketches_aod_create_cpp`, lg_k, num_values, seed)
}

aod_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_is_valid_cpp`, sketch)
}

aod_is_compact_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_is_compact_cpp`, sketch)
}

aod_update_doubles_cpp <- function(sketch, keys, values) {
  invisible(.Call(`_data_sketches_aod_update_doubles_cpp`, sketch, keys, values))
}

aod_update_strings_cpp <- function(sketch, keys, values) {
  invisible(.Call(`_data_sketches_aod_update_strings_cpp`, sketch, keys, values))
}

aod_get_lg_k_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_get_lg_k_cpp`, sketch)
}

aod_get_num_values_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_get_num_values_cpp`, sketch)
}

aod_merge_cpp <- function(sketch, other, lg_k, seed) {
  invisible(.Call(`_data_sketches_aod_merge_cpp`, sketch, other, lg_k, seed))
}

aod_get_estimate_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_get_estimate_cpp`, sketch)
}

aod_get_lower_bound_cpp <- function(sketch, num_std_dev) {
  .Call(`_data_sketches_aod_get_lower_bound_cpp`, sketch, num_std_dev)
}

aod_get_upper_bound_cpp <- function(sketch, num_std_dev) {
  .Call(`_data_sketches_aod_get_upper_bound_cpp`, sketch, num_std_dev)
}

aod_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_is_empty_cpp`, sketch)
}

aod_is_estimation_mode_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_is_estimation_mode_cpp`, sketch)
}

aod_get_theta_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_get_theta_cpp`, sketch)
}

aod_get_num_retained_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_get_num_retained_cpp`, sketch)
}

aod_is_ordered_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_is_ordered_cpp`, sketch)
}

aod_column_sums_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_column_sums_cpp`, sketch)
}

aod_to_string_cpp <- function(sketch, print_items) {
  .Call(`_data_sketches_aod_to_string_cpp`, sketch, print_items)
}

aod_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_aod_serialize_cpp`, sketch)
}

aod_deserialize_cpp <- function(bytes, seed) {
  .Call(`_data_sketches_aod_deserialize_cpp`, bytes, seed)
}

aod_union_cpp <- function(a, b, lg_k, seed, num_values) {
  .Call(`_data_sketches_aod_union_cpp`, a, b, lg_k, seed, num_values)
}

aod_intersection_cpp <- function(a, b, seed, num_values) {
  .Call(`_data_sketches_aod_intersection_cpp`, a, b, seed, num_values)
}

aod_a_not_b_cpp <- function(a, b, seed, num_values) {
  .Call(`_data_sketches_aod_a_not_b_cpp`, a, b, seed, num_values)
}

bf_create_by_accuracy_cpp <- function(max_items, fpp, seed) {
  .Call(`_data_sketches_bf_create_by_accuracy_cpp`, max_items, fpp, seed)
}

bf_create_by_size_cpp <- function(num_bits, num_hashes, seed) {
  .Call(`_data_sketches_bf_create_by_size_cpp`, num_bits, num_hashes, seed)
}

bf_is_valid_cpp <- function(filter) {
  .Call(`_data_sketches_bf_is_valid_cpp`, filter)
}

bf_update_doubles_cpp <- function(filter, items) {
  invisible(.Call(`_data_sketches_bf_update_doubles_cpp`, filter, items))
}

bf_update_strings_cpp <- function(filter, items) {
  invisible(.Call(`_data_sketches_bf_update_strings_cpp`, filter, items))
}

bf_query_doubles_cpp <- function(filter, items) {
  .Call(`_data_sketches_bf_query_doubles_cpp`, filter, items)
}

bf_query_strings_cpp <- function(filter, items) {
  .Call(`_data_sketches_bf_query_strings_cpp`, filter, items)
}

bf_query_and_update_doubles_cpp <- function(filter, items) {
  .Call(`_data_sketches_bf_query_and_update_doubles_cpp`, filter, items)
}

bf_query_and_update_strings_cpp <- function(filter, items) {
  .Call(`_data_sketches_bf_query_and_update_strings_cpp`, filter, items)
}

bf_get_capacity_cpp <- function(filter) {
  .Call(`_data_sketches_bf_get_capacity_cpp`, filter)
}

bf_get_num_hashes_cpp <- function(filter) {
  .Call(`_data_sketches_bf_get_num_hashes_cpp`, filter)
}

bf_get_seed_cpp <- function(filter) {
  .Call(`_data_sketches_bf_get_seed_cpp`, filter)
}

bf_get_bits_used_cpp <- function(filter) {
  .Call(`_data_sketches_bf_get_bits_used_cpp`, filter)
}

bf_is_empty_cpp <- function(filter) {
  .Call(`_data_sketches_bf_is_empty_cpp`, filter)
}

bf_reset_cpp <- function(filter) {
  invisible(.Call(`_data_sketches_bf_reset_cpp`, filter))
}

bf_is_compatible_cpp <- function(a, b) {
  .Call(`_data_sketches_bf_is_compatible_cpp`, a, b)
}

bf_union_cpp <- function(a, b) {
  invisible(.Call(`_data_sketches_bf_union_cpp`, a, b))
}

bf_intersect_cpp <- function(a, b) {
  invisible(.Call(`_data_sketches_bf_intersect_cpp`, a, b))
}

bf_invert_cpp <- function(filter) {
  invisible(.Call(`_data_sketches_bf_invert_cpp`, filter))
}

bf_to_string_cpp <- function(filter, print_filter) {
  .Call(`_data_sketches_bf_to_string_cpp`, filter, print_filter)
}

bf_serialize_cpp <- function(filter) {
  .Call(`_data_sketches_bf_serialize_cpp`, filter)
}

bf_deserialize_cpp <- function(bytes) {
  .Call(`_data_sketches_bf_deserialize_cpp`, bytes)
}

bf_suggest_num_filter_bits_cpp <- function(max_items, fpp) {
  .Call(`_data_sketches_bf_suggest_num_filter_bits_cpp`, max_items, fpp)
}

bf_suggest_num_hashes_cpp <- function(max_items, num_bits) {
  .Call(`_data_sketches_bf_suggest_num_hashes_cpp`, max_items, num_bits)
}

cm_create_cpp <- function(num_hashes, num_buckets, seed) {
  .Call(`_data_sketches_cm_create_cpp`, num_hashes, num_buckets, seed)
}

cm_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_cm_is_valid_cpp`, sketch)
}

cm_get_num_hashes_cpp <- function(sketch) {
  .Call(`_data_sketches_cm_get_num_hashes_cpp`, sketch)
}

cm_get_num_buckets_cpp <- function(sketch) {
  .Call(`_data_sketches_cm_get_num_buckets_cpp`, sketch)
}

cm_get_seed_cpp <- function(sketch) {
  .Call(`_data_sketches_cm_get_seed_cpp`, sketch)
}

cm_get_relative_error_cpp <- function(sketch) {
  .Call(`_data_sketches_cm_get_relative_error_cpp`, sketch)
}

cm_get_total_weight_cpp <- function(sketch) {
  .Call(`_data_sketches_cm_get_total_weight_cpp`, sketch)
}

cm_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_cm_is_empty_cpp`, sketch)
}

cm_update_doubles_cpp <- function(sketch, values, weights) {
  invisible(.Call(`_data_sketches_cm_update_doubles_cpp`, sketch, values, weights))
}

cm_update_strings_cpp <- function(sketch, values, weights) {
  invisible(.Call(`_data_sketches_cm_update_strings_cpp`, sketch, values, weights))
}

cm_get_estimate_doubles_cpp <- function(sketch, items) {
  .Call(`_data_sketches_cm_get_estimate_doubles_cpp`, sketch, items)
}

cm_get_estimate_strings_cpp <- function(sketch, items) {
  .Call(`_data_sketches_cm_get_estimate_strings_cpp`, sketch, items)
}

cm_get_lower_bound_doubles_cpp <- function(sketch, items) {
  .Call(`_data_sketches_cm_get_lower_bound_doubles_cpp`, sketch, items)
}

cm_get_lower_bound_strings_cpp <- function(sketch, items) {
  .Call(`_data_sketches_cm_get_lower_bound_strings_cpp`, sketch, items)
}

cm_get_upper_bound_doubles_cpp <- function(sketch, items) {
  .Call(`_data_sketches_cm_get_upper_bound_doubles_cpp`, sketch, items)
}

cm_get_upper_bound_strings_cpp <- function(sketch, items) {
  .Call(`_data_sketches_cm_get_upper_bound_strings_cpp`, sketch, items)
}

cm_merge_cpp <- function(sketch, other) {
  invisible(.Call(`_data_sketches_cm_merge_cpp`, sketch, other))
}

cm_to_string_cpp <- function(sketch) {
  .Call(`_data_sketches_cm_to_string_cpp`, sketch)
}

cm_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_cm_serialize_cpp`, sketch)
}

cm_deserialize_cpp <- function(bytes, seed) {
  .Call(`_data_sketches_cm_deserialize_cpp`, bytes, seed)
}

cm_suggest_num_buckets_cpp <- function(relative_error) {
  .Call(`_data_sketches_cm_suggest_num_buckets_cpp`, relative_error)
}

cm_suggest_num_hashes_cpp <- function(confidence) {
  .Call(`_data_sketches_cm_suggest_num_hashes_cpp`, confidence)
}

cpc_create_cpp <- function(lg_k, seed) {
  .Call(`_data_sketches_cpc_create_cpp`, lg_k, seed)
}

cpc_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_cpc_is_valid_cpp`, sketch)
}

cpc_update_doubles_cpp <- function(sketch, values) {
  invisible(.Call(`_data_sketches_cpc_update_doubles_cpp`, sketch, values))
}

cpc_update_strings_cpp <- function(sketch, values) {
  invisible(.Call(`_data_sketches_cpc_update_strings_cpp`, sketch, values))
}

cpc_merge_cpp <- function(sketch, other, seed) {
  invisible(.Call(`_data_sketches_cpc_merge_cpp`, sketch, other, seed))
}

cpc_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_cpc_is_empty_cpp`, sketch)
}

cpc_get_lg_k_cpp <- function(sketch) {
  .Call(`_data_sketches_cpc_get_lg_k_cpp`, sketch)
}

cpc_get_estimate_cpp <- function(sketch) {
  .Call(`_data_sketches_cpc_get_estimate_cpp`, sketch)
}

cpc_get_lower_bound_cpp <- function(sketch, kappa) {
  .Call(`_data_sketches_cpc_get_lower_bound_cpp`, sketch, kappa)
}

cpc_get_upper_bound_cpp <- function(sketch, kappa) {
  .Call(`_data_sketches_cpc_get_upper_bound_cpp`, sketch, kappa)
}

cpc_to_string_cpp <- function(sketch) {
  .Call(`_data_sketches_cpc_to_string_cpp`, sketch)
}

cpc_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_cpc_serialize_cpp`, sketch)
}

cpc_deserialize_cpp <- function(bytes, seed) {
  .Call(`_data_sketches_cpc_deserialize_cpp`, bytes, seed)
}

eb_create_cpp <- function(k, is_string) {
  .Call(`_data_sketches_eb_create_cpp`, k, is_string)
}

eb_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_eb_is_valid_cpp`, sketch)
}

eb_is_string_cpp <- function(sketch) {
  .Call(`_data_sketches_eb_is_string_cpp`, sketch)
}

eb_update_doubles_cpp <- function(sketch, items, weights) {
  invisible(.Call(`_data_sketches_eb_update_doubles_cpp`, sketch, items, weights))
}

eb_update_strings_cpp <- function(sketch, items, weights) {
  invisible(.Call(`_data_sketches_eb_update_strings_cpp`, sketch, items, weights))
}

eb_get_k_cpp <- function(sketch) {
  .Call(`_data_sketches_eb_get_k_cpp`, sketch)
}

eb_get_n_cpp <- function(sketch) {
  .Call(`_data_sketches_eb_get_n_cpp`, sketch)
}

eb_get_cumulative_weight_cpp <- function(sketch) {
  .Call(`_data_sketches_eb_get_cumulative_weight_cpp`, sketch)
}

eb_get_c_cpp <- function(sketch) {
  .Call(`_data_sketches_eb_get_c_cpp`, sketch)
}

eb_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_eb_is_empty_cpp`, sketch)
}

eb_result_doubles_cpp <- function(sketch) {
  .Call(`_data_sketches_eb_result_doubles_cpp`, sketch)
}

eb_result_strings_cpp <- function(sketch) {
  .Call(`_data_sketches_eb_result_strings_cpp`, sketch)
}

eb_merge_cpp <- function(sketch, other) {
  invisible(.Call(`_data_sketches_eb_merge_cpp`, sketch, other))
}

eb_to_string_cpp <- function(sketch, print_items) {
  .Call(`_data_sketches_eb_to_string_cpp`, sketch, print_items)
}

eb_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_eb_serialize_cpp`, sketch)
}

eb_deserialize_cpp <- function(bytes) {
  .Call(`_data_sketches_eb_deserialize_cpp`, bytes)
}

fi_create_cpp <- function(lg_max_map_size, lg_start_map_size) {
  .Call(`_data_sketches_fi_create_cpp`, lg_max_map_size, lg_start_map_size)
}

fi_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_fi_is_valid_cpp`, sketch)
}

fi_update_cpp <- function(sketch, items, weights) {
  invisible(.Call(`_data_sketches_fi_update_cpp`, sketch, items, weights))
}

fi_merge_cpp <- function(sketch, other) {
  invisible(.Call(`_data_sketches_fi_merge_cpp`, sketch, other))
}

fi_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_fi_is_empty_cpp`, sketch)
}

fi_get_num_active_items_cpp <- function(sketch) {
  .Call(`_data_sketches_fi_get_num_active_items_cpp`, sketch)
}

fi_get_total_weight_cpp <- function(sketch) {
  .Call(`_data_sketches_fi_get_total_weight_cpp`, sketch)
}

fi_get_maximum_error_cpp <- function(sketch) {
  .Call(`_data_sketches_fi_get_maximum_error_cpp`, sketch)
}

fi_get_epsilon_cpp <- function(sketch) {
  .Call(`_data_sketches_fi_get_epsilon_cpp`, sketch)
}

fi_get_estimate_cpp <- function(sketch, items) {
  .Call(`_data_sketches_fi_get_estimate_cpp`, sketch, items)
}

fi_get_lower_bound_cpp <- function(sketch, items) {
  .Call(`_data_sketches_fi_get_lower_bound_cpp`, sketch, items)
}

fi_get_upper_bound_cpp <- function(sketch, items) {
  .Call(`_data_sketches_fi_get_upper_bound_cpp`, sketch, items)
}

fi_get_frequent_items_cpp <- function(sketch, err_type, threshold) {
  .Call(`_data_sketches_fi_get_frequent_items_cpp`, sketch, err_type, threshold)
}

fi_to_string_cpp <- function(sketch, print_items) {
  .Call(`_data_sketches_fi_to_string_cpp`, sketch, print_items)
}

fi_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_fi_serialize_cpp`, sketch)
}

fi_deserialize_cpp <- function(bytes) {
  .Call(`_data_sketches_fi_deserialize_cpp`, bytes)
}

hll_create_cpp <- function(lg_k, type) {
  .Call(`_data_sketches_hll_create_cpp`, lg_k, type)
}

hll_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_hll_is_valid_cpp`, sketch)
}

hll_update_doubles_cpp <- function(sketch, values) {
  invisible(.Call(`_data_sketches_hll_update_doubles_cpp`, sketch, values))
}

hll_update_strings_cpp <- function(sketch, values) {
  invisible(.Call(`_data_sketches_hll_update_strings_cpp`, sketch, values))
}

hll_merge_cpp <- function(sketch, other) {
  invisible(.Call(`_data_sketches_hll_merge_cpp`, sketch, other))
}

hll_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_hll_is_empty_cpp`, sketch)
}

hll_is_compact_cpp <- function(sketch) {
  .Call(`_data_sketches_hll_is_compact_cpp`, sketch)
}

hll_get_lg_config_k_cpp <- function(sketch) {
  .Call(`_data_sketches_hll_get_lg_config_k_cpp`, sketch)
}

hll_get_target_type_cpp <- function(sketch) {
  .Call(`_data_sketches_hll_get_target_type_cpp`, sketch)
}

hll_get_estimate_cpp <- function(sketch) {
  .Call(`_data_sketches_hll_get_estimate_cpp`, sketch)
}

hll_get_lower_bound_cpp <- function(sketch, num_std_dev) {
  .Call(`_data_sketches_hll_get_lower_bound_cpp`, sketch, num_std_dev)
}

hll_get_upper_bound_cpp <- function(sketch, num_std_dev) {
  .Call(`_data_sketches_hll_get_upper_bound_cpp`, sketch, num_std_dev)
}

hll_to_string_cpp <- function(sketch, summary, detail, aux_detail, all) {
  .Call(`_data_sketches_hll_to_string_cpp`, sketch, summary, detail, aux_detail, all)
}

hll_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_hll_serialize_cpp`, sketch)
}

hll_deserialize_cpp <- function(bytes) {
  .Call(`_data_sketches_hll_deserialize_cpp`, bytes)
}

kll_doubles_create_cpp <- function(k) {
  .Call(`_data_sketches_kll_doubles_create_cpp`, k)
}

kll_doubles_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_doubles_is_valid_cpp`, sketch)
}

kll_doubles_update_cpp <- function(sketch, values) {
  invisible(.Call(`_data_sketches_kll_doubles_update_cpp`, sketch, values))
}

kll_doubles_merge_cpp <- function(sketch, other) {
  invisible(.Call(`_data_sketches_kll_doubles_merge_cpp`, sketch, other))
}

kll_doubles_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_doubles_is_empty_cpp`, sketch)
}

kll_doubles_is_estimation_mode_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_doubles_is_estimation_mode_cpp`, sketch)
}

kll_doubles_get_k_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_doubles_get_k_cpp`, sketch)
}

kll_doubles_get_n_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_doubles_get_n_cpp`, sketch)
}

kll_doubles_get_num_retained_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_doubles_get_num_retained_cpp`, sketch)
}

kll_doubles_get_min_item_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_doubles_get_min_item_cpp`, sketch)
}

kll_doubles_get_max_item_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_doubles_get_max_item_cpp`, sketch)
}

kll_doubles_get_quantiles_cpp <- function(sketch, ranks, inclusive) {
  .Call(`_data_sketches_kll_doubles_get_quantiles_cpp`, sketch, ranks, inclusive)
}

kll_doubles_get_ranks_cpp <- function(sketch, values, inclusive) {
  .Call(`_data_sketches_kll_doubles_get_ranks_cpp`, sketch, values, inclusive)
}

kll_doubles_get_pmf_cpp <- function(sketch, split_points, inclusive) {
  .Call(`_data_sketches_kll_doubles_get_pmf_cpp`, sketch, split_points, inclusive)
}

kll_doubles_get_cdf_cpp <- function(sketch, split_points, inclusive) {
  .Call(`_data_sketches_kll_doubles_get_cdf_cpp`, sketch, split_points, inclusive)
}

kll_doubles_rank_error_cpp <- function(sketch, as_pmf) {
  .Call(`_data_sketches_kll_doubles_rank_error_cpp`, sketch, as_pmf)
}

kll_doubles_to_string_cpp <- function(sketch, print_levels, print_items) {
  .Call(`_data_sketches_kll_doubles_to_string_cpp`, sketch, print_levels, print_items)
}

kll_doubles_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_doubles_serialize_cpp`, sketch)
}

kll_doubles_deserialize_cpp <- function(bytes) {
  .Call(`_data_sketches_kll_doubles_deserialize_cpp`, bytes)
}

kll_floats_create_cpp <- function(k) {
  .Call(`_data_sketches_kll_floats_create_cpp`, k)
}

kll_floats_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_floats_is_valid_cpp`, sketch)
}

kll_floats_update_cpp <- function(sketch, values) {
  invisible(.Call(`_data_sketches_kll_floats_update_cpp`, sketch, values))
}

kll_floats_merge_cpp <- function(sketch, other) {
  invisible(.Call(`_data_sketches_kll_floats_merge_cpp`, sketch, other))
}

kll_floats_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_floats_is_empty_cpp`, sketch)
}

kll_floats_is_estimation_mode_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_floats_is_estimation_mode_cpp`, sketch)
}

kll_floats_get_k_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_floats_get_k_cpp`, sketch)
}

kll_floats_get_n_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_floats_get_n_cpp`, sketch)
}

kll_floats_get_num_retained_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_floats_get_num_retained_cpp`, sketch)
}

kll_floats_get_min_item_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_floats_get_min_item_cpp`, sketch)
}

kll_floats_get_max_item_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_floats_get_max_item_cpp`, sketch)
}

kll_floats_get_quantiles_cpp <- function(sketch, ranks, inclusive) {
  .Call(`_data_sketches_kll_floats_get_quantiles_cpp`, sketch, ranks, inclusive)
}

kll_floats_get_ranks_cpp <- function(sketch, values, inclusive) {
  .Call(`_data_sketches_kll_floats_get_ranks_cpp`, sketch, values, inclusive)
}

kll_floats_get_pmf_cpp <- function(sketch, split_points, inclusive) {
  .Call(`_data_sketches_kll_floats_get_pmf_cpp`, sketch, split_points, inclusive)
}

kll_floats_get_cdf_cpp <- function(sketch, split_points, inclusive) {
  .Call(`_data_sketches_kll_floats_get_cdf_cpp`, sketch, split_points, inclusive)
}

kll_floats_rank_error_cpp <- function(sketch, as_pmf) {
  .Call(`_data_sketches_kll_floats_rank_error_cpp`, sketch, as_pmf)
}

kll_floats_to_string_cpp <- function(sketch, print_levels, print_items) {
  .Call(`_data_sketches_kll_floats_to_string_cpp`, sketch, print_levels, print_items)
}

kll_floats_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_kll_floats_serialize_cpp`, sketch)
}

kll_floats_deserialize_cpp <- function(bytes) {
  .Call(`_data_sketches_kll_floats_deserialize_cpp`, bytes)
}

req_create_cpp <- function(k, hra) {
  .Call(`_data_sketches_req_create_cpp`, k, hra)
}

req_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_req_is_valid_cpp`, sketch)
}

req_update_cpp <- function(sketch, values) {
  invisible(.Call(`_data_sketches_req_update_cpp`, sketch, values))
}

req_merge_cpp <- function(sketch, other) {
  invisible(.Call(`_data_sketches_req_merge_cpp`, sketch, other))
}

req_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_req_is_empty_cpp`, sketch)
}

req_is_estimation_mode_cpp <- function(sketch) {
  .Call(`_data_sketches_req_is_estimation_mode_cpp`, sketch)
}

req_get_k_cpp <- function(sketch) {
  .Call(`_data_sketches_req_get_k_cpp`, sketch)
}

req_is_hra_cpp <- function(sketch) {
  .Call(`_data_sketches_req_is_hra_cpp`, sketch)
}

req_get_n_cpp <- function(sketch) {
  .Call(`_data_sketches_req_get_n_cpp`, sketch)
}

req_get_num_retained_cpp <- function(sketch) {
  .Call(`_data_sketches_req_get_num_retained_cpp`, sketch)
}

req_get_min_item_cpp <- function(sketch) {
  .Call(`_data_sketches_req_get_min_item_cpp`, sketch)
}

req_get_max_item_cpp <- function(sketch) {
  .Call(`_data_sketches_req_get_max_item_cpp`, sketch)
}

req_get_quantiles_cpp <- function(sketch, ranks, inclusive) {
  .Call(`_data_sketches_req_get_quantiles_cpp`, sketch, ranks, inclusive)
}

req_get_ranks_cpp <- function(sketch, values, inclusive) {
  .Call(`_data_sketches_req_get_ranks_cpp`, sketch, values, inclusive)
}

req_get_pmf_cpp <- function(sketch, split_points, inclusive) {
  .Call(`_data_sketches_req_get_pmf_cpp`, sketch, split_points, inclusive)
}

req_get_cdf_cpp <- function(sketch, split_points, inclusive) {
  .Call(`_data_sketches_req_get_cdf_cpp`, sketch, split_points, inclusive)
}

req_rank_lower_bound_cpp <- function(sketch, ranks, num_std_dev) {
  .Call(`_data_sketches_req_rank_lower_bound_cpp`, sketch, ranks, num_std_dev)
}

req_rank_upper_bound_cpp <- function(sketch, ranks, num_std_dev) {
  .Call(`_data_sketches_req_rank_upper_bound_cpp`, sketch, ranks, num_std_dev)
}

req_to_string_cpp <- function(sketch, print_levels, print_items) {
  .Call(`_data_sketches_req_to_string_cpp`, sketch, print_levels, print_items)
}

req_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_req_serialize_cpp`, sketch)
}

req_deserialize_cpp <- function(bytes) {
  .Call(`_data_sketches_req_deserialize_cpp`, bytes)
}

td_create_cpp <- function(k) {
  .Call(`_data_sketches_td_create_cpp`, k)
}

td_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_td_is_valid_cpp`, sketch)
}

td_update_cpp <- function(sketch, values) {
  invisible(.Call(`_data_sketches_td_update_cpp`, sketch, values))
}

td_merge_cpp <- function(sketch, other) {
  invisible(.Call(`_data_sketches_td_merge_cpp`, sketch, other))
}

td_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_td_is_empty_cpp`, sketch)
}

td_get_k_cpp <- function(sketch) {
  .Call(`_data_sketches_td_get_k_cpp`, sketch)
}

td_get_total_weight_cpp <- function(sketch) {
  .Call(`_data_sketches_td_get_total_weight_cpp`, sketch)
}

td_get_min_value_cpp <- function(sketch) {
  .Call(`_data_sketches_td_get_min_value_cpp`, sketch)
}

td_get_max_value_cpp <- function(sketch) {
  .Call(`_data_sketches_td_get_max_value_cpp`, sketch)
}

td_get_quantiles_cpp <- function(sketch, ranks) {
  .Call(`_data_sketches_td_get_quantiles_cpp`, sketch, ranks)
}

td_get_ranks_cpp <- function(sketch, values) {
  .Call(`_data_sketches_td_get_ranks_cpp`, sketch, values)
}

td_get_pmf_cpp <- function(sketch, split_points) {
  .Call(`_data_sketches_td_get_pmf_cpp`, sketch, split_points)
}

td_get_cdf_cpp <- function(sketch, split_points) {
  .Call(`_data_sketches_td_get_cdf_cpp`, sketch, split_points)
}

td_to_string_cpp <- function(sketch, print_centroids) {
  .Call(`_data_sketches_td_to_string_cpp`, sketch, print_centroids)
}

td_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_td_serialize_cpp`, sketch)
}

td_deserialize_cpp <- function(bytes) {
  .Call(`_data_sketches_td_deserialize_cpp`, bytes)
}

theta_create_cpp <- function(lg_k, seed) {
  .Call(`_data_sketches_theta_create_cpp`, lg_k, seed)
}

theta_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_theta_is_valid_cpp`, sketch)
}

theta_is_compact_cpp <- function(sketch) {
  .Call(`_data_sketches_theta_is_compact_cpp`, sketch)
}

theta_update_doubles_cpp <- function(sketch, values) {
  invisible(.Call(`_data_sketches_theta_update_doubles_cpp`, sketch, values))
}

theta_update_strings_cpp <- function(sketch, values) {
  invisible(.Call(`_data_sketches_theta_update_strings_cpp`, sketch, values))
}

theta_get_lg_k_cpp <- function(sketch) {
  .Call(`_data_sketches_theta_get_lg_k_cpp`, sketch)
}

theta_merge_cpp <- function(sketch, other, lg_k, seed) {
  invisible(.Call(`_data_sketches_theta_merge_cpp`, sketch, other, lg_k, seed))
}

theta_get_estimate_cpp <- function(sketch) {
  .Call(`_data_sketches_theta_get_estimate_cpp`, sketch)
}

theta_get_lower_bound_cpp <- function(sketch, num_std_dev) {
  .Call(`_data_sketches_theta_get_lower_bound_cpp`, sketch, num_std_dev)
}

theta_get_upper_bound_cpp <- function(sketch, num_std_dev) {
  .Call(`_data_sketches_theta_get_upper_bound_cpp`, sketch, num_std_dev)
}

theta_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_theta_is_empty_cpp`, sketch)
}

theta_is_estimation_mode_cpp <- function(sketch) {
  .Call(`_data_sketches_theta_is_estimation_mode_cpp`, sketch)
}

theta_get_theta_cpp <- function(sketch) {
  .Call(`_data_sketches_theta_get_theta_cpp`, sketch)
}

theta_get_num_retained_cpp <- function(sketch) {
  .Call(`_data_sketches_theta_get_num_retained_cpp`, sketch)
}

theta_get_seed_hash_cpp <- function(sketch) {
  .Call(`_data_sketches_theta_get_seed_hash_cpp`, sketch)
}

theta_is_ordered_cpp <- function(sketch) {
  .Call(`_data_sketches_theta_is_ordered_cpp`, sketch)
}

theta_to_string_cpp <- function(sketch, print_items) {
  .Call(`_data_sketches_theta_to_string_cpp`, sketch, print_items)
}

theta_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_theta_serialize_cpp`, sketch)
}

theta_deserialize_cpp <- function(bytes, seed) {
  .Call(`_data_sketches_theta_deserialize_cpp`, bytes, seed)
}

theta_union_cpp <- function(a, b, lg_k, seed) {
  .Call(`_data_sketches_theta_union_cpp`, a, b, lg_k, seed)
}

theta_intersection_cpp <- function(a, b, seed) {
  .Call(`_data_sketches_theta_intersection_cpp`, a, b, seed)
}

theta_a_not_b_cpp <- function(a, b, seed) {
  .Call(`_data_sketches_theta_a_not_b_cpp`, a, b, seed)
}

theta_jaccard_cpp <- function(a, b, seed) {
  .Call(`_data_sketches_theta_jaccard_cpp`, a, b, seed)
}

vo_create_cpp <- function(k, is_string) {
  .Call(`_data_sketches_vo_create_cpp`, k, is_string)
}

vo_is_valid_cpp <- function(sketch) {
  .Call(`_data_sketches_vo_is_valid_cpp`, sketch)
}

vo_is_string_cpp <- function(sketch) {
  .Call(`_data_sketches_vo_is_string_cpp`, sketch)
}

vo_update_doubles_cpp <- function(sketch, items, weights) {
  invisible(.Call(`_data_sketches_vo_update_doubles_cpp`, sketch, items, weights))
}

vo_update_strings_cpp <- function(sketch, items, weights) {
  invisible(.Call(`_data_sketches_vo_update_strings_cpp`, sketch, items, weights))
}

vo_get_k_cpp <- function(sketch) {
  .Call(`_data_sketches_vo_get_k_cpp`, sketch)
}

vo_get_n_cpp <- function(sketch) {
  .Call(`_data_sketches_vo_get_n_cpp`, sketch)
}

vo_get_num_samples_cpp <- function(sketch) {
  .Call(`_data_sketches_vo_get_num_samples_cpp`, sketch)
}

vo_is_empty_cpp <- function(sketch) {
  .Call(`_data_sketches_vo_is_empty_cpp`, sketch)
}

vo_samples_doubles_cpp <- function(sketch) {
  .Call(`_data_sketches_vo_samples_doubles_cpp`, sketch)
}

vo_samples_strings_cpp <- function(sketch) {
  .Call(`_data_sketches_vo_samples_strings_cpp`, sketch)
}

vo_estimate_subset_sum_cpp <- function(sketch, indicator) {
  .Call(`_data_sketches_vo_estimate_subset_sum_cpp`, sketch, indicator)
}

vo_merge_cpp <- function(sketch, other, max_k) {
  invisible(.Call(`_data_sketches_vo_merge_cpp`, sketch, other, max_k))
}

vo_union_cpp <- function(a, b, max_k) {
  .Call(`_data_sketches_vo_union_cpp`, a, b, max_k)
}

vo_to_string_cpp <- function(sketch, print_items) {
  .Call(`_data_sketches_vo_to_string_cpp`, sketch, print_items)
}

vo_serialize_cpp <- function(sketch) {
  .Call(`_data_sketches_vo_serialize_cpp`, sketch)
}

vo_deserialize_cpp <- function(bytes) {
  .Call(`_data_sketches_vo_deserialize_cpp`, bytes)
}
