# Generated by tools/update-datasketches-cpp.R -- do not edit by hand.
# The vendored Apache DataSketches C++ release, used as `native_version` when
# writing sketch files (see persistence). Kept in lockstep with the headers by
# the updater script.
.datasketches_native_version <- "5.2.0"
